export const PLAN_ORDER = { premium: 0, gold: 1, classic: 2 } as const;

export type PlanType = keyof typeof PLAN_ORDER;

export const PLANS = {
  classic: {
    name: 'Classic',
    subtitle: 'Dijital Vitrin',
    price: '1.500',
    priceNum: 1500,
    color: '#8c8c8c',
    tagColor: 'default' as const,
    badge: null,
    description: 'Dijital vitrin: dizinde profil sayfası, temel görünürlük ve iletişim bilgileriniz.',
    features: [
      { text: 'Esnaf dizininde profil sayfası', included: true },
      { text: 'Telefon ve WhatsApp butonu', included: true },
      { text: 'Marka / model etiketleri', included: true },
      { text: 'Temel SEO görünürlüğü', included: true },
      { text: 'Parça talebi mesajları alma', included: false },
      { text: '"Gold Esnaf" rozeti', included: false },
      { text: 'Öncelikli sıralama', included: false },
      { text: '"Premium Esnaf" öne çıkan rozeti', included: false },
    ],
  },
  gold: {
    name: 'Gold',
    subtitle: 'Talep Erişimi',
    price: '2.500',
    priceNum: 2500,
    color: '#d4a017',
    tagColor: 'gold' as const,
    badge: 'Popüler',
    description: 'Talep erişimi: dijital vitrinin yanı sıra parça taleplerini alın ve Gold Esnaf rozeti kazanın.',
    features: [
      { text: 'Esnaf dizininde profil sayfası', included: true },
      { text: 'Telefon ve WhatsApp butonu', included: true },
      { text: 'Marka / model etiketleri', included: true },
      { text: 'Gelişmiş SEO görünürlüğü', included: true },
      { text: 'Parça talebi mesajları alma', included: true },
      { text: '"Gold Esnaf" rozeti', included: true },
      { text: 'Öncelikli sıralama', included: false },
      { text: '"Premium Esnaf" öne çıkan rozeti', included: false },
    ],
  },
  premium: {
    name: 'Premium',
    subtitle: 'Maksimum Görünürlük',
    price: '3.000',
    priceNum: 3000,
    color: '#6B3FA0',
    tagColor: 'purple' as const,
    badge: 'En Avantajlı',
    description: 'Maksimum görünürlük: tüm özellikler, öncelikli sıralama ve her yerde öne çıkan rozet.',
    features: [
      { text: 'Esnaf dizininde profil sayfası', included: true },
      { text: 'Telefon ve WhatsApp butonu', included: true },
      { text: 'Marka / model etiketleri', included: true },
      { text: 'Maksimum SEO görünürlüğü', included: true },
      { text: 'Parça talebi mesajları alma', included: true },
      { text: '"Gold Esnaf" rozeti', included: true },
      { text: 'Öncelikli sıralama', included: true },
      { text: '"Premium Esnaf" öne çıkan rozeti', included: true },
    ],
  },
} as const;
